### ISSUE TITLE
Error - Terraform Init

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-cp4ba-operator#8]
I tried to run the Terraform init which throws error

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Missing newline after argument
│ 
│ On variables.tf line 9: An argument definition must end with a newline.
╵

**Action Needed:**
 - Extra Double Quotes added in Line 9 
     -   default = ""ibm-operator-catalog"  "

**Comment by dineshchandrapandey** [comment]
Cross-checked variables.tf file
